export const browserCoreExamples = [
  "bobolt browser status",
  "bobolt browser start",
  "bobolt browser stop",
  "bobolt browser tabs",
  "bobolt browser open https://example.com",
  "bobolt browser focus abcd1234",
  "bobolt browser close abcd1234",
  "bobolt browser screenshot",
  "bobolt browser screenshot --full-page",
  "bobolt browser screenshot --ref 12",
  "bobolt browser snapshot",
  "bobolt browser snapshot --format aria --limit 200",
  "bobolt browser snapshot --efficient",
  "bobolt browser snapshot --labels",
];

export const browserActionExamples = [
  "bobolt browser navigate https://example.com",
  "bobolt browser resize 1280 720",
  "bobolt browser click 12 --double",
  'bobolt browser type 23 "hello" --submit',
  "bobolt browser press Enter",
  "bobolt browser hover 44",
  "bobolt browser drag 10 11",
  "bobolt browser select 9 OptionA OptionB",
  "bobolt browser upload /tmp/file.pdf",
  'bobolt browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "bobolt browser dialog --accept",
  'bobolt browser wait --text "Done"',
  "bobolt browser evaluate --fn '(el) => el.textContent' --ref 7",
  "bobolt browser console --level error",
  "bobolt browser pdf",
];
